CREATE table empresas( 
        IdEmpresa INTEGER PRIMARY KEY AUTOINCREMENT
      , RazonSocial TEXT NOT NULL UNIQUE
      , Empleados INTEGER NOT NULL
      );
	
INSERT INTO empresas (RazonSocial, Empleados) VALUES ('MICROSOFT CORPORATION', 123456), ('APPLE INC.', 23456), ('GOOGLE LLC', 34567), ('AMAZON.COM, INC.', 45678), ('FACEBOOK, INC.', 5678), ('INTERNATIONAL BUSINESS MACHINES CORPORATION', 678), ('INTEL CORPORATION', 7890), ('ORACLE CORPORATION', 8901), ('SAMSUNG ELECTRONICS CO., LTD.', 9012), ('NETFLIX, INC.', 1234), ('UBER TECHNOLOGIES, INC.', 2345), ('AIRBNB, INC.', 345), ('SPOTIFY TECHNOLOGY S.A.', 456), ('ADOBE INC.', 567), ('TWITTER, INC.', 6789), ('LINKEDIN CORPORATION', 789), ('HUAWEI TECHNOLOGIES CO., LTD.', 890), ('TESLA, INC.', 9012), ('NVIDIA CORPORATION', 1234), ('QUALCOMM INCORPORATED', 2345), ('IBM CORPORATION', 3456), ('MICRON TECHNOLOGY, INC.', 45), ('CISCO SYSTEMS, INC.', 5678), ('HEWLETT PACKARD ENTERPRISE COMPANY', 678), ('SAP SE', 7890), ('DELL TECHNOLOGIES INC.', 8901), ('ALPHABET INC.', 90);